#!/usr/bin/env bash
if [ -z "$SAGE_LOCAL" ]; then 
    echo >&2 "Error: SAGE_LOCAL undefined - exiting..."
    echo >&2 "Maybe run 'sage -sh'?"
    exit 1  
fi

# Remove previous installation (if any):
rm -rf "$SAGE_LOCAL"/lib/python/site-packages/ia || exit 1


cd src

# Build:
sage -pip install pymysql

python setup.py build
if [ $? -ne 0 ]; then
    echo >&2 "Error building 'ia'."
    exit 1
fi

# Install:
python setup.py install
if [ $? -ne 0 ]; then
    echo >&2 "Error installing 'ia'."
    exit 1
fi

### oder stattdessen:??
# manuell bauen:

 #  sage setup.py build_ext --inplace
#python setup.py build_ext --inplace
